### ISSUE TITLE
How to use it in frontend

### ISSUE THREAD

**Issue by vallettea** [doowb/ngraph.frombinary#1]
Hello,
thanks for this module.

I can't figure how to use this in frontend:
```
var load = require('ngraph.frombinary');
var Graph = require('ngraph.graph');

var graph = load(new Graph({uniqueLinkIds: false}), {cwd: './data/'});

console.log(graph.getNodesCount())
```

works in node but when i browserify it and try to run it in frontend, it complains it cannot read `meta.json`.

Any help appreciated.

**Comment by doowb** [comment]
When I created this, it was to do the opposite of what `ngraph.tobinary` was doing, which writes to the filesystem directly. I never intended it to be used in the browser.

Because of the use of `fs` and `path` with `process.cwd()`, I'm not sure if it would be possible to alias any other libraries to make this work in the browser.

What I would do is have a server that runs this when you request the graph from an endpoint, then `ngraph.frombinary` can be run on the server and the results can be streamed to the client (browser).

I hope this helps.

**Comment by vallettea** [comment]
thanks for the answer
